name: PopCraft
main: org.popcraft.popcraft.PopCraft
version: 1.8.3.1
description: Specially crafted plugin for the PopCraft server.
author: pop4959
authors: [waffelmonster]
website: popcraft.enjin.com

commands:
   popcraft:
      description: Allows various administrative tasks.
      aliases: pc
      permission: popcraft.popcraft
      permission-message: You can't use this.
      usage: "§cUsage: /popcraft <args>"
   magicmessage:
      description: Set an automatic broadcast message.
      aliases: mm
      permission: popcraft.magicmessage
      permission-message: You can't use this.
      usage: "§cUsage: /magicmessage [start <message>/stop/show/force]"
   fireworks:
      description: Spawns fireworks.
      aliases: [fw, flare]
      permission: popcraft.fireworks
      permission-message: You can't use this.
      usage: "§cUsage: /fireworks random/list/color [fade] [effect] [type] [height]"
   tpr:
      description: Teleport to a random location.
      aliases: [wild, rtp]
      permission: popcraft.tpr
      permission-message: You can't use this.
      usage: "§cUsage: /tpr"
   listgen:
      description: Generate a list of all players on the server.
      aliases: lg
      permission: popcraft.listgen
      permission-message: You can't use this.
      usage: "§cUsage: /listgen"
   me:
      description: Describes an action in the context of the player.
      permission: popcraft.me
      permission-message: You can't use this.
      usage: "§cUsage: /me <action>"
   donate:
      description: Displays information about donating, and donations.
      aliases: [d, donation, donations, donating, buy]
      permission: popcraft.donate
      permission-message: You can't use this.
      usage: "§cUsage: /donate"
   trail:
      description: Set a movement trail effect!
      aliases: tr
      permission: popcraft.trail
      permission-message: You can't use this.
      usage: "§cUsage: /trail <type/list/clear> [style/damage...]"
   staff:
      description: Broadcast, or privately message to all staff members on the server.
      aliases: [st, mods]
      permission: popcraft.staff
      permission-message: You can't use this.
      usage: "§cUsage: /staff <message>"
   generateworld:
      description: Allows you to generate the world.
      permission: popcraft.generateworld
      permission-message: You can't use this.
      usage: "§cUsage: /generateworld"
   music:
      description: Allows you to play a music discs.
      permission: popcraft.music
      permission-message: You can't use this.
      usage: "§cUsage: /music <disc [speed]/list/stop>"
   pvp:
      description: Allows you to toggle PvP.
      permission: popcraft.pvp
      permission-message: You can't use this.
      usage: "§cUsage: /pvp"
   worldspawn:
      description: Allows you to set the world's spawnpoint.
      permission: popcraft.worldspawn
      permission-message: You can't use this.
      usage: "§cUsage: /worldspawn"
   textures:
      description: Allows you to use the PopCraft texture pack.
      aliases: [tx, resource, resources, resourcepack, texturepack]
      permission: popcraft.textures
      permission-message: You can't use this.
      usage: "§cUsage: /textures"
   getscore:
      description: Allows you to get the score of a user.
      permission: popcraft.getscore
      permission-message: You can't use this.
      usage: "§cUsage: /getscore <username>"
   supersay:
      description: Allows the server to speak in the context of user format.
      aliases: [ssay, ss]
      permission: popcraft.supersay
      permission-message: You can't use this.
      usage: "§cUsage: /supersay <message>"
   pop:
      description: Allows the server to speak in the context of the owner.
      aliases: p
      permission: popcraft.pop
      permission-message: You can't use this.
      usage: "§cUsage: /pop <message>"
   lockdown:
      description: Toggles the ability of players to join the server.
      permission: popcraft.lockdown
      permission-message: You can't use this.
      usage: "§cUsage: /lockdown"
   plugins:
      description: Allows you to see the server's plugins.
      aliases: pl
      permission: popcraft.plugins
      permission-message: You can't use this.
      usage: "§cUsage: /plugins"
   version:
      description: Allows you to see the server's version.
      aliases: ver
      permission: popcraft.version
      permission-message: You can't use this.
      usage: "§cUsage: /version"
   piggyback:
      description: Toggles the ability of others to piggyback on you.
      aliases: ride
      permission: popcraft.piggyback
      permission-message: You can't use this.
      usage: "§cUsage: /piggyback"
   lol:
      description: You thought this was an actual command.
      permission: jonslogger.lol
      permission-message: You don't have the permission you dummy.
   lolreload:
      description: Just some old random command.
      permission: jonslogger.lol
      permission-message: You don't have the permission you bigger dummy.
   handicap:
      description: Handicap yourself!
      permission: popcraft.handicap
      permission-message: You can't use this.
      usage: "§cUsage: /handicap <hp>"
   vote:
      description: Vote for PopCraft as the best server!
      permission: popcraft.vote
      permission-message: You can't use this.
      usage: "§cUsage: /vote"
   aura:
      description: Set an aura for your player!
      permission: popcraft.aura
      permission-message: You can't use this.
      usage: "§cUsage: /aura <type/list/clear> [damage]"
   glow:
      description: Toggles player glow effect.
      permission: popcraft.glow
      permission-message: You can't use this.
      usage: "§cUsage: /glow"
   spoof:
      description: Emulates real chat and status messages.
      permission: popcraft.spoof
      permission-message: You can't use this.
      usage: "§cUsage: /spoof <join/quit/afk/no-afk>"
   discord:
      description: Displays the Discord join link.
      permission: popcraft.discord
      permission-message: You can't use this.
      usage: "§cUsage: /discord"
   teamspeak:
      description: Displays the TeamSpeak server address.
      permission: popcraft.teamspeak
      permission-message: You can't use this.
      usage: "§cUsage: /teamspeak"
   ticket:
      description: Manage and send report tickets to staff.
      aliases: [report, tickets]
      permission: popcraft.ticket
      permission-message: You can't use this.
      usage: "§cUsage: /ticket"
permissions:
  popcraft.me:
    description: Allows you to write a message in third person.
    default: true
  popcraft.donate:
    description: Allows you to view donation info.
    default: true
  popcraft.trail.*:
    description: Allows you to set custom trails for any player.
    children:
      popcraft.trail: true
      popcraft.trail.extended: true
  popcraft.jumper:
    description: Allows you to jump high with a feather.
    default: false